runtime: python39

env_variables:
  SECRET_KEY: "your-super-secret-key-change-this-in-production"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always 